[theme]
primaryColor = "#563573"  # Grape purple
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#a3acae"  # Lighter grayish teal
textColor = "#000000"  # Black text
font = "sans serif